from(bucket: "monitoramento")
  |> range(start: 2024-06-17T00:00:00Z, stop: 2024-06-18T00:00:00Z)
  |> filter(fn: (r) => r._measurement == "sensor_reading")
  |> filter(fn: (r) => r._field == "temperature" or r._field == "humidity" or r._field == "co2" or r._field == "battery")
  |> keep(columns: ["_time", "sensorId", "room", "status", "_field", "_value"])